services:
  app:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=vehicle_tracker
      - DB_USER=postgres
      - DB_PASSWORD=1234

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: vehicle_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
